CREATE USER 'administrator'@'%'  IDENTIFIED BY '23555523';
GRANT ALL PRIVILEGES ON *.* TO 'administrator'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'komercijalista'@'%'  IDENTIFIED BY '23555523';
GRANT ALL PRIVILEGES ON *.* TO 'komercijalista'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'dizajnerlastis'@'%'  IDENTIFIED BY '23555523';
GRANT ALL PRIVILEGES ON *.* TO 'dizajnerlastis'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'dizajnertkanje'@'%'  IDENTIFIED BY '23555523';
GRANT ALL PRIVILEGES ON *.* TO 'dizajnertkanje'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'dizajnerstampa'@'%'  IDENTIFIED BY '23555523';
GRANT ALL PRIVILEGES ON *.* TO 'dizajnerstampa'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'magacioner'@'%'  IDENTIFIED BY '23555523';
GRANT ALL PRIVILEGES ON *.* TO 'magacioner'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'sefproizvodnje'@'%'  IDENTIFIED BY '23555523';
GRANT ALL PRIVILEGES ON *.* TO 'sefproizvodnje'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'sefsmene'@'%'  IDENTIFIED BY '23555523';
GRANT ALL PRIVILEGES ON *.* TO 'sefsmene'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'knjigovodjaf'@'%'  IDENTIFIED BY '23555523';
GRANT ALL PRIVILEGES ON *.* TO 'knjigovodjaf'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;